### ISSUE TITLE
Downloaded latest release and nothing rendered in either tab CPU or MEM

### ISSUE THREAD

**Issue by AddictArts** [ningt/iStats#1]
Does it need sudo? Thanks

**Comment by AddictArts** [comment]
![no-stats](https://cloud.githubusercontent.com/assets/911906/17937182/24f514f4-69d6-11e6-8385-1d70962dc407.png)

**Comment by ningt** [comment]
No `sudo` is required.

Sorry for the late reply, I was quite busy last week. Could u do me a favour again? Could u send me the result of running `top -stats pid,cpu,command -o cpu`? I need to identify whether the problem is at `os-usage` or this repo. Thank u!

**Comment by AddictArts** [comment]
```
Processes: 359 total, 2 running, 16 stuck, 341 sleeping, 2865 threads                                                                                  13:48:44
Load Avg: 2.68, 2.45, 2.37  CPU usage: 3.35% user, 2.75% sys, 93.89% idle   SharedLibs: 16M resident, 14M data, 0B linkedit.
MemRegions: 155056 total, 3967M resident, 79M private, 1372M shared. PhysMem: 16G used (2846M wired), 195M unused.
VM: 1054G vsize, 1063M framework vsize, 287303(0) swapins, 578000(0) swapouts. Networks: packets: 2402594/1915M in, 2143522/631M out.
Disks: 10461461/184G read, 9334724/191G written.

PID                                                %CPU                                             COMMAND
259                                                8.1                                              Terminal
999                                                6.5                                              firefox
196                                                4.3                                              WindowServer
5459                                               4.0                                              top
73111                                              4.0                                              EpicGamesLaunche
91963                                              3.9                                              Atom
0                                                  3.4                                              kernel_task
3456                                               2.1                                              Google Chrome He
3434                                               1.8                                              Google Chrome He
65840                                              1.1                                              com.apple.WebKit
1944                                               0.6                                              LCCDaemon
634                                                0.3                                              HyperDock Helper
5255                                               0.3                                              Safari
4062                                               0.3                                              HyperTerm
78369                                              0.2                                              WMail Helper
3394                                               0.2                                              Google Chrome
628                                                0.2                                              Google Drive
564                                                0.2                                              NotificationCent
1014                                               0.2                                              plugin-container
96739                                              0.2                                              Dropbox
3414                                               0.2                                              Google Chrome He
5278                                               0.2                                              com.apple.WebKit
3444                                               0.2                                              Google Chrome He
3443                                               0.2                                              Google Chrome He
3436                                               0.1                                              Google Chrome He
3435                                               0.1                                              Google Chrome He
3445                                               0.1                                              Google Chrome He
56                                                 0.1                                              mds
3453                                               0.1                                              Google Chrome He
78356                                              0.1                                              WMail
5300                                               0.0                                              com.apple.WebKit
3419                                               0.0                                              Google Chrome He
```

**Comment by ningt** [comment]
@AddictArts  Can u try with the latest release? It should work now.

**Comment by AddictArts** [comment]
Version 1.3.1 was the version I reported this issue against. I downloaded it again and tried and I still don't see anything in the window.

**Comment by AddictArts** [comment]
The issue is os-usage. I tried from the App folder in Resources and I get nothing out of os-usage using their example code.

**Comment by AddictArts** [comment]
I upgraded to EL Capitan and viola it works now, so it is a Yosemite plus os-usage issue. You can close this. Thanks

**Comment by ningt** [comment]
Oh good, I will try fix it once I have a Yosemite.
